# Global settings
#

# span/riemen in gui opnemen.
# time in seconds:  6:34.0  --> 6*60+34.0=396.0
Boats:
  {
# men
  M1x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:34.0
          time : 396.0, tempo : 36,  type : scull, driveTime : 0.70, angleIn : -66.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 540.0 },
  M2x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:04.0
          time : 364.0, tempo : 36,  type : scull, driveTime : 0.67, angleIn : -66.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 540.0 },
  M4x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 5:34.0
          time : 334.0, tempo : 38,  type : scull, driveTime : 0.65, angleIn : -66.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.32, PowerUp70 : 12.0, PowerDown70 : 38.0, power : 540.0 },
  M2- : { span : 1.15, inboard : 0.85, outboard : 2.0,
  # 6:12.0
          time : 372.0, tempo : 36,  type : sweep, driveTime : 0.70, angleIn : -54.0, angleOut : 36.0, slipIn : 9.0, slipOut :  9.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 10.0, PowerDown70 : 26.0, power : 540.0 },
  M4- : { span : 1.15, inboard : 0.85, outboard : 2.0,
  # 5:40.0
          time : 340.0, tempo : 38,  type : sweep, driveTime : 0.67, angleIn : -54.0, angleOut : 36.0, slipIn : 9.0, slipOut :  9.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 10.0, PowerDown70 : 29.0, power : 540.0 },
  M8+ : { span : 1.15, inboard : 0.85, outboard : 2.0,
  # 5:20.0
          time : 320.0, tempo : 38,  type : sweep, driveTime : 0.63, angleIn : -54.0, angleOut : 36.0, slipIn : 9.0, slipOut :  9.0,
          seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.32, PowerUp70 : 10.0, PowerDown70 : 32.0, power : 540.0 },
          
# women
  W1x  : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 7:12.0
           time : 432.0, tempo : 34,  type : scull, driveTime : 0.70, angleIn : -62.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 54.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 350.0 },
  LW1x : { span : 1.6,  inboard : 0.86, outboard : 2.0,
  # 7:28.0
           time : 448.0, tempo : 34,  type : scull, driveTime : 0.70, angleIn : -60.0, angleOut : 42.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 50.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 290.0 },
  W2x  : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:38.0
           time : 398.0, tempo : 34,  type : scull, driveTime : 0.67, angleIn : -62.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 54.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 350.0 },
  LW2x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:48.0
           time : 408.0, tempo : 34,  type : scull, driveTime : 0.67, angleIn : -60.0, angleOut : 42.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 50.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 290.0 },
  W2- : { span : 1.15, inboard : 0.85, outboard : 2.0,
  # 6:51.0
          time : 411.0, tempo : 34,  type : sweep, driveTime : 0.70, angleIn : -54.0, angleOut : 32.0, slipIn : 9.0, slipOut :  9.0,
          seatDist : 54.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 10.0, PowerDown70 : 26.0, power : 350.0 },
  W8+ : { span : 1.15, inboard : 0.85, outboard : 2.0,
  # 5:54.0
          time : 354.0, tempo : 36,  type : sweep, driveTime : 0.63, angleIn : -54.0, angleOut : 32.0, slipIn : 9.0, slipOut :  9.0,
          seatDist : 54.0, ratioF : 0.55, peakPower@ : 0.32, PowerUp70 : 10.0, PowerDown70 : 32.0, power : 350.0 },

# junior
#   o.a. tijden nog niet goed!!
  JM1x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 7:04.0
           time : 424.0, tempo : 34,  type : scull, driveTime : 0.70, angleIn : -66.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 58.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 420.0 },
  JW2x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:48.0
           time : 408.0, tempo : 34,  type : scull, driveTime : 0.67, angleIn : -60.0, angleOut : 42.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 50.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 290.0 },
  JW1x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 7:34.0
           time : 454.0, tempo : 32,  type : scull, driveTime : 0.70, angleIn : -62.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 52.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 300.0 },
  JM2x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:04.0
           time : 364.0, tempo : 36,  type : scull, driveTime : 0.67, angleIn : -66.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 60.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 540.0 },
  JW4x : { span : 1.6,  inboard : 0.88, outboard : 2.0,
  # 6:48.0
           time : 408.0, tempo : 34,  type : scull, driveTime : 0.67, angleIn : -60.0, angleOut : 42.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 50.0, ratioF : 0.55, peakPower@ : 0.35, PowerUp70 : 12.0, PowerDown70 : 35.0, power : 290.0 },

# experiment met korte riemen/span
  KL1x : { span : 1.4,  inboard : 0.78, outboard : 1.72,
  # 7:34.0
           time : 454.0, tempo : 32,  type : scull, driveTime : 0.70, angleIn : -62.0, angleOut : 44.0, slipIn : 6.0, slipOut : 12.0,
           seatDist : 52.0, ratioF : 0.55, peakPower@ : 0.38, PowerUp70 : 12.0, PowerDown70 : 32.0, power : 300.0 },
  }

  
RowerModel:
  {
  shoulderWitdh   : 0.2,         # fraction of lenght
  shoulderOffset  : 0.1,          # distance shoulder before seat in fraction of lenght
  threshCatch     : 0.1,         # fraction of max force
  threshFinish    : 0.1,         # fraction of max force
  }

