# List of Rowers 
#    name: full name, length weight, year of birth, category, 2k score

Rowers:
  {
  # dummy names
  P1: [Full Name. 185, 88, 2002, H, 6:20.4],
  P2: [Full Name. 185, 88, 2002, H, 6:20.4],
  P3: [Full Name. 185, 88, 2002, H, 6:20.4],
  P4: [Full Name. 185, 88, 2002, H, 6:20.4],
  P5: [Full Name. 185, 88, 2002, H, 6:20.4],
  P6: [Full Name. 185, 88, 2002, H, 6:20.4],
  P8: [Full Name. 185, 88, 2002, H, 6:20.4],

  #
  JBl: [Jan Boterletter, 185, 88, 2002, H, 7:01.0],
  }


