# template of session info YAML file

# State of this session
#   initial
#   completely filled from traces data
State: initial

# number of rowers (generated)
RowerCnt: 1
   
# Timestamp of last update of this file
Timestamp: 2001-12-14 21:59:43.10 -5

# start points for pieces in the csv file (by concatenation csv files)
CsvPieces : []

# First 2 header rows from the csv-file
Header  : []
Header2 : []
uniqHeader: []

# Boat type (scull or sweep, boat type)
ScullSweep: 'scull'

# Generated list with for each stroke the time and rating,  derived from GateAngle?
#    tijd tussen twee opgaande nuldoorgangen, eerste als de tijd
# stilliggen (<10) als NaN?
Tempi :
  - [1000, 10]
  - [1300, 10]
  - [1680, 13]
  

# Marked pieces: list of name, (start, end) , (cnt, average rating), startlist
Pieces: []

# Video info:
#   filename in videos directory
#   videoPos:  position in the video  (red line)
#   dataPos, position in the data (blue line)
#   piece name (not yet)
Video:
  - No file yet
  - 0
  - 0
  - videopiece
