# template of session info YAML file

# State of this session
#   initial
#   completely filled from traces data
State: initial

# Name or description of the crew
CrewInfo:
   The Crew

# Only the first RowerCnt values will be used
#  name, year, length, weight
Rowers:
  - [R 1, 2000, 180, 90]
  - [R 2, 2000, 180, 90]
  - [R 3, 2000, 180, 90]
  - [R 4, 2000, 180, 90]
  - [R 5, 2000, 180, 90]
  - [R 6, 2000, 180, 90]
  - [R 7, 2000, 180, 90]
  - [R 8, 2000, 180, 90]

# number of rowers (generated)
RowerCnt: 1
   
Misc:
   Extra info about the session

# Timestamp of last update of this file
Timestamp: 2001-12-14 21:59:43.10 -5

# Powerline data set (also for index file)
Powerline: powerline data set file

# Powerline trace export
Traces: row004107-000001D_traces

# Speed and distance calibration
Calibration: 1.0

# start points for pieces in the csv file (by concatenation csv files)
CsvPieces : []

# First 2 header rows from the csv-file
Header  : []
Header2 : []
uniqHeader: []

# Boat type (scull or sweep, boat type)
ScullSweep: 'scull'
BoatType: 'M1x'

# Generated list with for each stroke the time and rating,  derived from GateAngle?
#    tijd tussen twee opgaande nuldoorgangen, eerste als de tijd
# stilliggen (<10) als NaN?
Tempi :
  - [1000, 10]
  - [1300, 10]
  - [1680, 13]
  

# Marked pieces: list of name, (start, length) , (cnt, average rating) (generated)
Pieces: []

# filename in videos directory
# index in data en index in video
# name of piece
Video:
  - None
  - 0
  - 0
  - video
